logging:
  level:
    org.springframework.security: DEBUG
security:
  sessions: ALWAYS
zuul:
  routes:
    ui:
      url: http://172.30.37.163:8080
      sensitive-headers:
    ui2:
      url: http://172.30.147.187:8080
      sensitive-headers:  
    ui3:
      url: http://172.30.51.38:8080
      sensitive-headers:  
    admin:
      url: http://172.30.194.37:8080
      sensitive-headers:
    resource:
      url: http://172.30.134.55:8080
      sensitive-headers:

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.30.166.215:3306/raghu
    username: raghu
    password: raghu
    continueOnError: true
    initialize: false
    initialSize: 0
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    minIdle: 0

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:   
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false