logging:
  level:
    org.springframework.security: DEBUG
security:
  sessions: ALWAYS
zuul:
  routes:
    ui:
      url: http://172.30.86.241:8080
      sensitive-headers:
    ui2:
      url: http://172.30.42.194:8080
      sensitive-headers:  
    ui3:
      url: http://172.30.209.21:8080
      sensitive-headers:  
    admin:
      url: http://172.30.253.111:8080
      sensitive-headers:
    resource:
      url: http://172.30.174.173:8080
      sensitive-headers:

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/persondb
    username: root
    password: accion123!@#
    continueOnError: true
    initialize: false
    initialSize: 0
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    minIdle: 0

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:   
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false