logging:
  level:
    org.springframework.security: DEBUG
security:
  sessions: ALWAYS
zuul:
  routes:
    ui:
      url: http://${ui1_secret_ip}:8080
      sensitive-headers:
    ui2:
      url: http://${ui2_secret_ip}:8080
      sensitive-headers:  
    ui3:
      url: http://${ui3_secret_ip}:8080
      sensitive-headers:  
    admin:
      url: http://${admin_secret_ip}:8080
      sensitive-headers:
    resource:
      url: http://${resource_secret_ip}:8080
      sensitive-headers:

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${my_sql_secret_ip}:${my_sql_secret_port}/${my_sql_secret_db}
    username: ${my_sql_secret_username}
    password: ${my_sql_secret_password}
    continueOnError: true
    initialize: false
    initialSize: 0
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    minIdle: 0

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:   
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false